---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgBjov+mmVrunxLTpq/qdo67+cGFnox3mtv4OCm6EvrWOdK42gKbvTEbN030U6GLpb2cGD5dODYCxD+lTQU9QYiYPE/47Qx65O6rBzE8/hDeHYoTVr8RDhe8GdXqG3h+owQVTGNZ6lpjOzY5l9iSzQ/X2TLMyMzRWK0w1EQf17tmP+hXFPCak+i9ELUMJhSSXI83Sp7eDfbkPIPwG1d0p/pPer02Z5Tjn9Ty79ZUiAwLlMZ/C6fzmaYdWN4Y1QNFwI1GUpt3gi3pQfnV/v4zu2tZe+XMO2e8Q0U68xw7DFaiyznBY6th7mw+E9/RSXVIpeTFBQYl/U6RqZnK2lBfNxJbTJ5X2YeXnsUXfDK39EQtYykE7zt0QMJEsY7AWU29GUdVAcNmuVhIVAc0PWeTzrpb536pIIh8kjCHFC47Vv4Sv8VO3eW+sQDgnc6o6d8J9d1V/3VmMEcT7tps1b7VISG3SXHPt1I2t9AsbxcrHDHiG++qHo1FgowzDt9Mo3r7jnq3/F8uGnEzswHYKAylz5XHnBf2HOOF4ifLEDd6fHBUURNMHw76sFJLF7w7+iPVSZN6GjFsgcUXPHEuZxdBvaP67yL+VDyigIa+I6i8lBlWvnSmcTq5NMx/iWH5XPlmCbJ/kRZBKzCLsrQ2K2H/kNt2mmNqn83tK8cBysWsjD/Ch1+GqFQd5JyCXtQNKyTtl5OmWSFzhRuyvSFP/klJgjTAHQLzGtn2iJ1u/KLwFqLTaPoEvqmqQ/0r
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
