- hosts: masters
  vars_files:
    - "../../../LaunchZones/K8s/global-config.vars"
  become: yes # Run as root
  become_user: "{{ become_user_setting }}"
  tasks:
    - name: Pre-Launch Task ... Package already deployed?
      shell: |
        kubectl get namespace {{ nginxingress_namespace }} --ignore-not-found
      register: nginxingress_alreadydeployed_check
      ignore_errors: yes
      args:
        executable: /bin/bash
    - block:
        - name: Pre-Launch Task ... Add Nginxingress Repo
          kubernetes.core.helm_repository:
            name: ingress-nginx
            repo_url: "{{ nginxingress_helm_chart_url }}"
        - name: Pre-Launch Task ... Install Nginxingress
          kubernetes.core.helm:
            name: ingress-nginx
            namespace: "{{ nginxingress_namespace }}"
            chart_ref: "{{ nginxingress_chart_ref }}"
            create_namespace: true
            wait: true
      when: nginxingress_alreadydeployed_check.stdout == ""
