apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: dev
spec:
  project: appbundle-project-dev
  source:
    chart: bitnami/nginx
    repoURL: https://charts.bitnami.com/bitnami
    helm:
      releaseName: bitnami