apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  project: appbundle-project-dev
  source:
    chart: bitnami/nginx
    repoURL: https://charts.bitnami.com/bitnami
    helm:
      releaseName: bitnami
  destination:
    name: development-admin@development
    namespace: dev