---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgAq+Dodq5osacKksBqukA7nhJo47sN+B/X7ohHvgqzADaFUOHP0d3GaO+T2ETXVyaDi1VHIxyv9R/09Rqsjm1Eqs97jVjWHfU0DQAtyyO7wBkuG7gsi46SdyTNYxNyEXUN8/diwmCO3okf21qoP01DnK+aOk0vPWbGtnC4czr9jrGKxC7XJqn9jqmp4LwnGeD7hudRPz4HOgls4y99G27zpVQsGl1QG8UmlCLku/2gfI9bG2EXzfH6mYZ1GbjhBWoLYMVHcBx44Rm12xuhVydouMbxmmDp58HkV73/I963ApAJevhSB9RLri/GBkUaXcMwYNldVhQscJ+TMn2fnZg79gFReVzvX45w0YprqnE12TE8eMB+A6nZbK7i0J+/r3OIoqdt67KN/o2iYFLzq8ft17AEnZutuRp9T2rE1LdhG8mmXsfQ7XpfSwbKsnQWLr9HZ/yDNvvLYFBBFGKor6ZC/Ga/nxZlvHdNlnADfXWwX3z8FO9ZrRAFCkYU/yvrLDJQ+BCNCt05bmb2QKlGk9qSuLTCI2tDIr0kXZe2ZWCQ7LmiYrY37V3mWKnw8mHOtpAesffVU7BKcQZYch+cBFT0J7+PNJ66yXd+KrEvXT408sCwk9EMboUWfxTJaqXfuUzYVlPmVxHNcEVS0aR3rYQo0J4L7e0DBFJiWIJEThHuB8vE/FonUGwnJ+sqZKDtCv3G4zX4ddrqB4/Oon/U2IWDLtrYZSLbAa99NHK0D
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
