apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wger
  namespace: argocd
spec:
  project: appbundle-project-dev
  source:
    repoURL: https://wger-project.github.io/helm-charts  # Directly use the provided URL
    chart: wger
    targetRevision: 0.2.0  # Specify the version of the chart you want to deploy
    helm:
      releaseName: wger
  destination:
    name: in-cluster
    namespace: wger
  syncPolicy:
    automated:
      prune: true
      selfHeal: true