---
- hosts: all
  become: yes
  vars_files:
    - "../../../LaunchZones/K8s/global-config.vars"
  tasks:
    - name: Uninstall stuff
      shell: |
        sudo kubeadm reset --force
        sudo apt-get purge --allow-change-held-packages -y kubeadm kubectl kubelet kubernetes-cni
        rm -rf /home/{{ become_user_setting | default(ansible_env.USER) }}/.kube
        rm -rf /etc/cni /etc/kubernetes /var/lib/dockershim /var/lib/etcd /var/lib/kubelet /var/lib/etcd2/ /var/run/kubernetes ~/.kube/*
        rm -rf /var/lib/docker /etc/docker /var/run/docker.sock
        rm -f /etc/apparmor.d/docker /etc/systemd/system/etcd*
        iptables -F && iptables -X
        iptables -t nat -F && iptables -t nat -X
        iptables -t raw -F && iptables -t raw -X
        iptables -t mangle -F && iptables -t mangle -X
    - name: Restart
      reboot:
