apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: DevOps/Pipelines/Argocd/Apps/Dev
    repoURL: https://github.com/011000100110111101101111/Nexus-2.0
    targetRevision: HEAD