apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-production-appbundle
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: production
    name: in-cluster
  project: production-project
  source:
    path: DevOps/Pipelines/Argocd/Apps/Prod
    repoURL: https://github.com/011000100110111101101111/Nexus-2.0
    targetRevision: HEAD