- import_playbook: ../../Kubernetes/Deployments/BaseCluster/install.yml
- import_playbook: ../../Kubernetes/Deployments/Metallb/basic.yml
- import_playbook: ../../Kubernetes/Deployments/Longhorn/basic.yml
- import_playbook: ../../Kubernetes/Deployments/Nginxingress/basic.yml
- import_playbook: ../../Kubernetes/Deployments/Certmanager/basic.yml
- import_playbook: ../../Kubernetes/Deployments/Argocd/with-tls.yml
